export interface CountryPricing {
  name: string
  flag: string
  prices: {
    USD: number
    GBP: number
    EUR: number
  }
  additionalClassPrice: number
}

// Pricing data based on WIPO NICE Classification - All prices in USD
export const countryPricingData: Record<string, CountryPricing> = {
  // Europe
  "European Union": {
    name: "European Union",
    flag: "eu",
    prices: { USD: 1550, GBP: 1165, EUR: 1335 },
    additionalClassPrice: 366,
  },
  Germany: {
    name: "Germany",
    flag: "de",
    prices: { USD: 865, GBP: 645, EUR: 740 },
    additionalClassPrice: 431,
  },
  Spain: {
    name: "Spain",
    flag: "es",
    prices: { USD: 565, GBP: 425, EUR: 485 },
    additionalClassPrice: 332,
  },
  "United Kingdom": {
    name: "United Kingdom",
    flag: "gb",
    prices: { USD: 910, GBP: 685, EUR: 785 },
    additionalClassPrice: 259,
  },
  France: {
    name: "France",
    flag: "fr",
    prices: { USD: 665, GBP: 500, EUR: 575 },
    additionalClassPrice: 164,
  },
  Italy: {
    name: "Italy",
    flag: "it",
    prices: { USD: 920, GBP: 690, EUR: 790 },
    additionalClassPrice: 155,
  },
  Benelux: {
    name: "Benelux",
    flag: "be",
    prices: { USD: 795, GBP: 595, EUR: 685 },
    additionalClassPrice: 164,
  },
  Portugal: {
    name: "Portugal",
    flag: "pt",
    prices: { USD: 910, GBP: 685, EUR: 785 },
    additionalClassPrice: 228,
  },
  Greece: {
    name: "Greece",
    flag: "gr",
    prices: { USD: 735, GBP: 550, EUR: 635 },
    additionalClassPrice: 491,
  },
  "Bosnia and Herzegovina": {
    name: "Bosnia and Herzegovina",
    flag: "ba",
    prices: { USD: 655, GBP: 490, EUR: 565 },
    additionalClassPrice: 147,
  },

  // North America
  "United States": {
    name: "United States",
    flag: "us",
    prices: { USD: 1010, GBP: 755, EUR: 865 },
    additionalClassPrice: 499,
  },
  Canada: {
    name: "Canada",
    flag: "ca",
    prices: { USD: 1370, GBP: 1030, EUR: 1180 },
    additionalClassPrice: 129,
  },
  Mexico: {
    name: "Mexico",
    flag: "mx",
    prices: { USD: 685, GBP: 515, EUR: 590 },
    additionalClassPrice: 466,
  },

  // South America
  Argentina: {
    name: "Argentina",
    flag: "ar",
    prices: { USD: 460, GBP: 345, EUR: 395 },
    additionalClassPrice: 301,
  },
  Bolivia: {
    name: "Bolivia",
    flag: "bo",
    prices: { USD: 775, GBP: 585, EUR: 670 },
    additionalClassPrice: 504,
  },
  Brazil: {
    name: "Brazil",
    flag: "br",
    prices: { USD: 645, GBP: 485, EUR: 555 },
    additionalClassPrice: 361,
  },
  Chile: {
    name: "Chile",
    flag: "cl",
    prices: { USD: 690, GBP: 515, EUR: 590 },
    additionalClassPrice: 430,
  },
  Colombia: {
    name: "Colombia",
    flag: "co",
    prices: { USD: 795, GBP: 595, EUR: 685 },
    additionalClassPrice: 422,
  },
  Ecuador: {
    name: "Ecuador",
    flag: "ec",
    prices: { USD: 630, GBP: 475, EUR: 545 },
    additionalClassPrice: 474,
  },
  Paraguay: {
    name: "Paraguay",
    flag: "py",
    prices: { USD: 565, GBP: 425, EUR: 485 },
    additionalClassPrice: 344,
  },
  Peru: {
    name: "Peru",
    flag: "pe",
    prices: { USD: 665, GBP: 500, EUR: 575 },
    additionalClassPrice: 491,
  },
  Uruguay: {
    name: "Uruguay",
    flag: "uy",
    prices: { USD: 605, GBP: 455, EUR: 520 },
    additionalClassPrice: 258,
  },
  Venezuela: {
    name: "Venezuela",
    flag: "ve",
    prices: { USD: 605, GBP: 455, EUR: 520 },
    additionalClassPrice: 440,
  },

  // Central America
  Belize: {
    name: "Belize",
    flag: "bz",
    prices: { USD: 915, GBP: 685, EUR: 785 },
    additionalClassPrice: 845,
  },
  "Costa Rica": {
    name: "Costa Rica",
    flag: "cr",
    prices: { USD: 530, GBP: 400, EUR: 455 },
    additionalClassPrice: 258,
  },
  "El Salvador": {
    name: "El Salvador",
    flag: "sv",
    prices: { USD: 570, GBP: 430, EUR: 490 },
    additionalClassPrice: 556,
  },
  Guatemala: {
    name: "Guatemala",
    flag: "gt",
    prices: { USD: 600, GBP: 450, EUR: 515 },
    additionalClassPrice: 448,
  },
  Honduras: {
    name: "Honduras",
    flag: "hn",
    prices: { USD: 685, GBP: 515, EUR: 590 },
    additionalClassPrice: 652,
  },
  Nicaragua: {
    name: "Nicaragua",
    flag: "ni",
    prices: { USD: 620, GBP: 465, EUR: 535 },
    additionalClassPrice: 603,
  },
  Panama: {
    name: "Panama",
    flag: "pa",
    prices: { USD: 620, GBP: 465, EUR: 535 },
    additionalClassPrice: 379,
  },

  // Caribbean
  Anguilla: {
    name: "Anguilla",
    flag: "ai",
    prices: { USD: 1010, GBP: 755, EUR: 865 },
    additionalClassPrice: 371,
  },
  "Antigua and Barbuda": {
    name: "Antigua and Barbuda",
    flag: "ag",
    prices: { USD: 760, GBP: 570, EUR: 655 },
    additionalClassPrice: 284,
  },
  Aruba: {
    name: "Aruba",
    flag: "aw",
    prices: { USD: 945, GBP: 705, EUR: 810 },
    additionalClassPrice: 147,
  },
  Bahamas: {
    name: "Bahamas",
    flag: "bs",
    prices: { USD: 1075, GBP: 805, EUR: 925 },
    additionalClassPrice: 806,
  },
  Barbados: {
    name: "Barbados",
    flag: "bb",
    prices: { USD: 1400, GBP: 1050, EUR: 1205 },
    additionalClassPrice: 991,
  },
  Bermuda: {
    name: "Bermuda",
    flag: "bm",
    prices: { USD: 1770, GBP: 1330, EUR: 1520 },
    additionalClassPrice: 1323,
  },
  "BES Islands": {
    name: "BES Islands",
    flag: "bq",
    prices: { USD: 875, GBP: 655, EUR: 750 },
    additionalClassPrice: 171,
  },
  "British Virgin Islands": {
    name: "British Virgin Islands",
    flag: "vg",
    prices: { USD: 1000, GBP: 750, EUR: 860 },
    additionalClassPrice: 414,
  },
  "Cayman Islands": {
    name: "Cayman Islands",
    flag: "ky",
    prices: { USD: 1240, GBP: 930, EUR: 1070 },
    additionalClassPrice: 302,
  },
  Cuba: {
    name: "Cuba",
    flag: "cu",
    prices: { USD: 1375, GBP: 1030, EUR: 1185 },
    additionalClassPrice: 629,
  },
  Curacao: {
    name: "Curacao",
    flag: "cw",
    prices: { USD: 1210, GBP: 905, EUR: 1040 },
    additionalClassPrice: 172,
  },
  Dominica: {
    name: "Dominica",
    flag: "dm",
    prices: { USD: 1025, GBP: 770, EUR: 880 },
    additionalClassPrice: 457,
  },
  "Dominican Republic": {
    name: "Dominican Republic",
    flag: "do",
    prices: { USD: 620, GBP: 465, EUR: 535 },
    additionalClassPrice: 361,
  },
  Grenada: {
    name: "Grenada",
    flag: "gd",
    prices: { USD: 1145, GBP: 860, EUR: 985 },
    additionalClassPrice: 241,
  },
  Guyana: {
    name: "Guyana",
    flag: "gy",
    prices: { USD: 565, GBP: 425, EUR: 485 },
    additionalClassPrice: 181,
  },
  Haiti: {
    name: "Haiti",
    flag: "ht",
    prices: { USD: 735, GBP: 550, EUR: 635 },
    additionalClassPrice: 371,
  },
  Jamaica: {
    name: "Jamaica",
    flag: "jm",
    prices: { USD: 1230, GBP: 925, EUR: 1060 },
    additionalClassPrice: 306,
  },
  Montserrat: {
    name: "Montserrat",
    flag: "ms",
    prices: { USD: 740, GBP: 555, EUR: 640 },
    additionalClassPrice: 271,
  },
  "Puerto Rico": {
    name: "Puerto Rico",
    flag: "pr",
    prices: { USD: 815, GBP: 615, EUR: 705 },
    additionalClassPrice: 586,
  },
  "Saint Kitts and Nevis": {
    name: "Saint Kitts and Nevis",
    flag: "kn",
    prices: { USD: 1070, GBP: 800, EUR: 920 },
    additionalClassPrice: 336,
  },
  "Saint Lucia": {
    name: "Saint Lucia",
    flag: "lc",
    prices: { USD: 1025, GBP: 770, EUR: 880 },
    additionalClassPrice: 336,
  },
  "Saint Vincent and the Grenadines": {
    name: "Saint Vincent and the Grenadines",
    flag: "vc",
    prices: { USD: 655, GBP: 490, EUR: 565 },
    additionalClassPrice: 491,
  },
  "Sint Maarten": {
    name: "Sint Maarten",
    flag: "sx",
    prices: { USD: 1255, GBP: 940, EUR: 1080 },
    additionalClassPrice: 172,
  },
  Suriname: {
    name: "Suriname",
    flag: "sr",
    prices: { USD: 875, GBP: 655, EUR: 750 },
    additionalClassPrice: 138,
  },
  "Trinidad and Tobago": {
    name: "Trinidad and Tobago",
    flag: "tt",
    prices: { USD: 830, GBP: 620, EUR: 710 },
    additionalClassPrice: 215,
  },
  "Turks and Caicos Islands": {
    name: "Turks and Caicos Islands",
    flag: "tc",
    prices: { USD: 2130, GBP: 1600, EUR: 1830 },
    additionalClassPrice: 1603,
  },

  // Africa
  Algeria: {
    name: "Algeria",
    flag: "dz",
    prices: { USD: 990, GBP: 745, EUR: 850 },
    additionalClassPrice: 853,
  },
  Angola: {
    name: "Angola",
    flag: "ao",
    prices: { USD: 1050, GBP: 790, EUR: 905 },
    additionalClassPrice: 905,
  },
  ARIPO: {
    name: "ARIPO",
    flag: "zw",
    prices: { USD: 3150, GBP: 2365, EUR: 2710 },
    additionalClassPrice: 2716,
  },
  Botswana: {
    name: "Botswana",
    flag: "bw",
    prices: { USD: 1090, GBP: 820, EUR: 935 },
    additionalClassPrice: 939,
  },
  Burundi: {
    name: "Burundi",
    flag: "bi",
    prices: { USD: 1550, GBP: 1165, EUR: 1335 },
    additionalClassPrice: 1336,
  },
  Djibouti: {
    name: "Djibouti",
    flag: "dj",
    prices: { USD: 2050, GBP: 1540, EUR: 1765 },
    additionalClassPrice: 1767,
  },
  Egypt: {
    name: "Egypt",
    flag: "eg",
    prices: { USD: 765, GBP: 575, EUR: 660 },
    additionalClassPrice: 659,
  },
  Ethiopia: {
    name: "Ethiopia",
    flag: "et",
    prices: { USD: 1290, GBP: 970, EUR: 1110 },
    additionalClassPrice: 1112,
  },
  Gambia: {
    name: "Gambia",
    flag: "gm",
    prices: { USD: 1350, GBP: 1015, EUR: 1160 },
    additionalClassPrice: 1163,
  },
  Ghana: {
    name: "Ghana",
    flag: "gh",
    prices: { USD: 1500, GBP: 1125, EUR: 1290 },
    additionalClassPrice: 1293,
  },
  Kenya: {
    name: "Kenya",
    flag: "ke",
    prices: { USD: 1600, GBP: 1200, EUR: 1380 },
    additionalClassPrice: 1379,
  },
  Libya: {
    name: "Libya",
    flag: "ly",
    prices: { USD: 1100, GBP: 825, EUR: 945 },
    additionalClassPrice: 952,
  },
  Madagascar: {
    name: "Madagascar",
    flag: "mg",
    prices: { USD: 1050, GBP: 790, EUR: 905 },
    additionalClassPrice: 905,
  },
  Morocco: {
    name: "Morocco",
    flag: "ma",
    prices: { USD: 1050, GBP: 790, EUR: 905 },
    additionalClassPrice: 905,
  },
  Mauritania: {
    name: "Mauritania",
    flag: "mr",
    prices: { USD: 1190, GBP: 895, EUR: 1025 },
    additionalClassPrice: 1026,
  },
  Mozambique: {
    name: "Mozambique",
    flag: "mz",
    prices: { USD: 1050, GBP: 790, EUR: 905 },
    additionalClassPrice: 905,
  },
  Namibia: {
    name: "Namibia",
    flag: "na",
    prices: { USD: 1100, GBP: 825, EUR: 945 },
    additionalClassPrice: 952,
  },
  Nigeria: {
    name: "Nigeria",
    flag: "ng",
    prices: { USD: 1150, GBP: 865, EUR: 990 },
    additionalClassPrice: 991,
  },
  OAPI: {
    name: "OAPI",
    flag: "sn",
    prices: { USD: 1690, GBP: 1270, EUR: 1455 },
    additionalClassPrice: 1457,
  },
  "DR Congo": {
    name: "DR Congo",
    flag: "cd",
    prices: { USD: 1200, GBP: 900, EUR: 1030 },
    additionalClassPrice: 1034,
  },
  Rwanda: {
    name: "Rwanda",
    flag: "rw",
    prices: { USD: 1350, GBP: 1015, EUR: 1160 },
    additionalClassPrice: 1163,
  },
  Seychelles: {
    name: "Seychelles",
    flag: "sc",
    prices: { USD: 1150, GBP: 865, EUR: 990 },
    additionalClassPrice: 991,
  },
  "South Africa": {
    name: "South Africa",
    flag: "za",
    prices: { USD: 1110, GBP: 835, EUR: 955 },
    additionalClassPrice: 957,
  },
  Sudan: {
    name: "Sudan",
    flag: "sd",
    prices: { USD: 1050, GBP: 790, EUR: 905 },
    additionalClassPrice: 905,
  },
  "Tanzania (TANU)": {
    name: "Tanzania (TANU)",
    flag: "tz",
    prices: { USD: 1000, GBP: 750, EUR: 860 },
    additionalClassPrice: 862,
  },
  "Tanzania (ZAN)": {
    name: "Tanzania (ZAN)",
    flag: "tz",
    prices: { USD: 1050, GBP: 790, EUR: 905 },
    additionalClassPrice: 905,
  },
  Tunisia: {
    name: "Tunisia",
    flag: "tn",
    prices: { USD: 990, GBP: 745, EUR: 850 },
    additionalClassPrice: 853,
  },
  Uganda: {
    name: "Uganda",
    flag: "ug",
    prices: { USD: 1850, GBP: 1390, EUR: 1590 },
    additionalClassPrice: 1590,
  },
  Zambia: {
    name: "Zambia",
    flag: "zm",
    prices: { USD: 1300, GBP: 975, EUR: 1120 },
    additionalClassPrice: 1116,
  },
  Zimbabwe: {
    name: "Zimbabwe",
    flag: "zw",
    prices: { USD: 1350, GBP: 1015, EUR: 1160 },
    additionalClassPrice: 1163,
  },

  // Asia and Middle East
  Afghanistan: {
    name: "Afghanistan",
    flag: "af",
    prices: { USD: 865, GBP: 645, EUR: 740 },
    additionalClassPrice: 940,
  },
  "Saudi Arabia": {
    name: "Saudi Arabia",
    flag: "sa",
    prices: { USD: 2820, GBP: 2115, EUR: 2425 },
    additionalClassPrice: 2112,
  },
  Armenia: {
    name: "Armenia",
    flag: "am",
    prices: { USD: 1495, GBP: 1120, EUR: 1285 },
    additionalClassPrice: 1121,
  },
  Azerbaijan: {
    name: "Azerbaijan",
    flag: "az",
    prices: { USD: 1000, GBP: 750, EUR: 860 },
    additionalClassPrice: 405,
  },
  Bahrain: {
    name: "Bahrain",
    flag: "bh",
    prices: { USD: 3015, GBP: 2260, EUR: 2590 },
    additionalClassPrice: 2259,
  },
  Bangladesh: {
    name: "Bangladesh",
    flag: "bd",
    prices: { USD: 890, GBP: 670, EUR: 765 },
    additionalClassPrice: 668,
  },
  Bhutan: {
    name: "Bhutan",
    flag: "bt",
    prices: { USD: 690, GBP: 515, EUR: 595 },
    additionalClassPrice: 328,
  },
  Brunei: {
    name: "Brunei",
    flag: "bn",
    prices: { USD: 865, GBP: 645, EUR: 740 },
    additionalClassPrice: 646,
  },
  Cambodia: {
    name: "Cambodia",
    flag: "kh",
    prices: { USD: 725, GBP: 545, EUR: 625 },
    additionalClassPrice: 542,
  },
  "Hong Kong": {
    name: "Hong Kong",
    flag: "hk",
    prices: { USD: 980, GBP: 735, EUR: 840 },
    additionalClassPrice: 423,
  },
  India: {
    name: "India",
    flag: "in",
    prices: { USD: 660, GBP: 495, EUR: 570 },
    additionalClassPrice: 388,
  },
  Indonesia: {
    name: "Indonesia",
    flag: "id",
    prices: { USD: 1140, GBP: 855, EUR: 980 },
    additionalClassPrice: 823,
  },
  Iran: {
    name: "Iran",
    flag: "ir",
    prices: { USD: 1725, GBP: 1295, EUR: 1485 },
    additionalClassPrice: 423,
  },
  "Iraq (Baghdad)": {
    name: "Iraq (Baghdad)",
    flag: "iq",
    prices: { USD: 1740, GBP: 1305, EUR: 1495 },
    additionalClassPrice: 258,
  },
  "Iraq (Kurdistan)": {
    name: "Iraq (Kurdistan)",
    flag: "iq",
    prices: { USD: 2010, GBP: 1510, EUR: 1730 },
    additionalClassPrice: 1516,
  },
  Japan: {
    name: "Japan",
    flag: "jp",
    prices: { USD: 775, GBP: 585, EUR: 670 },
    additionalClassPrice: 431,
  },
  Jordan: {
    name: "Jordan",
    flag: "jo",
    prices: { USD: 1495, GBP: 1120, EUR: 1285 },
    additionalClassPrice: 1121,
  },
  Kazakhstan: {
    name: "Kazakhstan",
    flag: "kz",
    prices: { USD: 920, GBP: 690, EUR: 790 },
    additionalClassPrice: 371,
  },
  Kyrgyzstan: {
    name: "Kyrgyzstan",
    flag: "kg",
    prices: { USD: 850, GBP: 640, EUR: 730 },
    additionalClassPrice: 449,
  },
  "South Korea": {
    name: "South Korea",
    flag: "kr",
    prices: { USD: 805, GBP: 605, EUR: 690 },
    additionalClassPrice: 517,
  },
  Kuwait: {
    name: "Kuwait",
    flag: "kw",
    prices: { USD: 2095, GBP: 1570, EUR: 1800 },
    additionalClassPrice: 1565,
  },
  Laos: {
    name: "Laos",
    flag: "la",
    prices: { USD: 735, GBP: 550, EUR: 635 },
    additionalClassPrice: 551,
  },
  Lebanon: {
    name: "Lebanon",
    flag: "lb",
    prices: { USD: 1010, GBP: 755, EUR: 865 },
    additionalClassPrice: 405,
  },
  Macao: {
    name: "Macao",
    flag: "mo",
    prices: { USD: 885, GBP: 665, EUR: 760 },
    additionalClassPrice: 665,
  },
  Malaysia: {
    name: "Malaysia",
    flag: "my",
    prices: { USD: 1325, GBP: 990, EUR: 1140 },
    additionalClassPrice: 836,
  },
  Maldives: {
    name: "Maldives",
    flag: "mv",
    prices: { USD: 1025, GBP: 770, EUR: 880 },
    additionalClassPrice: 423,
  },
  Mongolia: {
    name: "Mongolia",
    flag: "mn",
    prices: { USD: 780, GBP: 585, EUR: 670 },
    additionalClassPrice: 414,
  },
  Myanmar: {
    name: "Myanmar",
    flag: "mm",
    prices: { USD: 725, GBP: 545, EUR: 625 },
    additionalClassPrice: 449,
  },
  Nepal: {
    name: "Nepal",
    flag: "np",
    prices: { USD: 725, GBP: 545, EUR: 625 },
    additionalClassPrice: 543,
  },
  "North Korea": {
    name: "North Korea",
    flag: "kp",
    prices: { USD: 1555, GBP: 1165, EUR: 1335 },
    additionalClassPrice: 491,
  },
  Oman: {
    name: "Oman",
    flag: "om",
    prices: { USD: 1645, GBP: 1235, EUR: 1415 },
    additionalClassPrice: 1233,
  },
  Pakistan: {
    name: "Pakistan",
    flag: "pk",
    prices: { USD: 865, GBP: 645, EUR: 740 },
    additionalClassPrice: 594,
  },
  "Palestine (Gaza)": {
    name: "Palestine (Gaza)",
    flag: "ps",
    prices: { USD: 1010, GBP: 755, EUR: 865 },
    additionalClassPrice: 754,
  },
  "Palestine (West Bank)": {
    name: "Palestine (West Bank)",
    flag: "ps",
    prices: { USD: 965, GBP: 725, EUR: 830 },
    additionalClassPrice: 724,
  },
  Philippines: {
    name: "Philippines",
    flag: "ph",
    prices: { USD: 750, GBP: 560, EUR: 645 },
    additionalClassPrice: 457,
  },
  Qatar: {
    name: "Qatar",
    flag: "qa",
    prices: { USD: 2510, GBP: 1880, EUR: 2160 },
    additionalClassPrice: 1884,
  },
  Singapore: {
    name: "Singapore",
    flag: "sg",
    prices: { USD: 1025, GBP: 770, EUR: 880 },
    additionalClassPrice: 646,
  },
  Syria: {
    name: "Syria",
    flag: "sy",
    prices: { USD: 2015, GBP: 1510, EUR: 1730 },
    additionalClassPrice: 1516,
  },
  "Sri Lanka": {
    name: "Sri Lanka",
    flag: "lk",
    prices: { USD: 685, GBP: 515, EUR: 590 },
    additionalClassPrice: 513,
  },
  Taiwan: {
    name: "Taiwan",
    flag: "tw",
    prices: { USD: 815, GBP: 615, EUR: 705 },
    additionalClassPrice: 612,
  },
  Tajikistan: {
    name: "Tajikistan",
    flag: "tj",
    prices: { USD: 2010, GBP: 1510, EUR: 1730 },
    additionalClassPrice: 1516,
  },
  Thailand: {
    name: "Thailand",
    flag: "th",
    prices: { USD: 1380, GBP: 1035, EUR: 1190 },
    additionalClassPrice: 862,
  },
  Turkey: {
    name: "Turkey",
    flag: "tr",
    prices: { USD: 645, GBP: 485, EUR: 555 },
    additionalClassPrice: 228,
  },
  Turkmenistan: {
    name: "Turkmenistan",
    flag: "tm",
    prices: { USD: 1145, GBP: 860, EUR: 985 },
    additionalClassPrice: 466,
  },
  "United Arab Emirates": {
    name: "United Arab Emirates",
    flag: "ae",
    prices: { USD: 2990, GBP: 2245, EUR: 2570 },
    additionalClassPrice: 2138,
  },
  Uzbekistan: {
    name: "Uzbekistan",
    flag: "uz",
    prices: { USD: 1540, GBP: 1155, EUR: 1330 },
    additionalClassPrice: 508,
  },
  Vietnam: {
    name: "Vietnam",
    flag: "vn",
    prices: { USD: 575, GBP: 430, EUR: 495 },
    additionalClassPrice: 427,
  },
  Yemen: {
    name: "Yemen",
    flag: "ye",
    prices: { USD: 1840, GBP: 1380, EUR: 1580 },
    additionalClassPrice: 1379,
  },
  China: {
    name: "China",
    flag: "cn",
    prices: { USD: 520, GBP: 390, EUR: 445 },
    additionalClassPrice: 388,
  },
  Israel: {
    name: "Israel",
    flag: "il",
    prices: { USD: 1495, GBP: 1120, EUR: 1285 },
    additionalClassPrice: 1121,
  },

  // Oceania
  "Papua New Guinea": {
    name: "Papua New Guinea",
    flag: "pg",
    prices: { USD: 930, GBP: 700, EUR: 800 },
    additionalClassPrice: 1035,
  },
  Fiji: {
    name: "Fiji",
    flag: "fj",
    prices: { USD: 1850, GBP: 1390, EUR: 1590 },
    additionalClassPrice: 862,
  },
  Tonga: {
    name: "Tonga",
    flag: "to",
    prices: { USD: 1700, GBP: 1275, EUR: 1460 },
    additionalClassPrice: 957,
  },
}

// Helper function to get top requested countries
export const getTopCountries = (): CountryPricing[] => {
  return [
    countryPricingData["European Union"],
    countryPricingData["United States"],
    countryPricingData["Germany"],
    countryPricingData["Spain"],
    countryPricingData["United Kingdom"],
    countryPricingData["China"],
  ]
}

// Helper function to get countries by region
export const getCountriesByRegion = () => {
  return {
    "North America": [countryPricingData["United States"], countryPricingData["Canada"], countryPricingData["Mexico"]],
    Europe: [
      countryPricingData["European Union"],
      countryPricingData["Spain"],
      countryPricingData["France"],
      countryPricingData["United Kingdom"],
      countryPricingData["Italy"],
      countryPricingData["Germany"],
      countryPricingData["Portugal"],
      countryPricingData["Greece"],
      countryPricingData["Benelux"],
      countryPricingData["Bosnia and Herzegovina"],
    ],
    "South America": [
      countryPricingData["Argentina"],
      countryPricingData["Brazil"],
      countryPricingData["Chile"],
      countryPricingData["Colombia"],
      countryPricingData["Ecuador"],
      countryPricingData["Paraguay"],
      countryPricingData["Peru"],
      countryPricingData["Uruguay"],
      countryPricingData["Venezuela"],
      countryPricingData["Bolivia"],
    ],
    "Central America": [
      countryPricingData["Costa Rica"],
      countryPricingData["Panama"],
      countryPricingData["Guatemala"],
      countryPricingData["El Salvador"],
      countryPricingData["Honduras"],
      countryPricingData["Nicaragua"],
      countryPricingData["Belize"],
    ],
    Caribbean: [
      countryPricingData["Jamaica"],
      countryPricingData["Dominican Republic"],
      countryPricingData["Cuba"],
      countryPricingData["Bahamas"],
      countryPricingData["Barbados"],
      countryPricingData["Trinidad and Tobago"],
      countryPricingData["Aruba"],
      countryPricingData["Curacao"],
      countryPricingData["Antigua and Barbuda"],
      countryPricingData["Saint Lucia"],
      countryPricingData["Grenada"],
      countryPricingData["Saint Kitts and Nevis"],
      countryPricingData["Dominica"],
      countryPricingData["Saint Vincent and the Grenadines"],
      countryPricingData["Bermuda"],
      countryPricingData["Cayman Islands"],
      countryPricingData["British Virgin Islands"],
      countryPricingData["Turks and Caicos Islands"],
      countryPricingData["Anguilla"],
      countryPricingData["Montserrat"],
      countryPricingData["Sint Maarten"],
      countryPricingData["BES Islands"],
      countryPricingData["Guyana"],
      countryPricingData["Suriname"],
      countryPricingData["Haiti"],
      countryPricingData["Puerto Rico"],
    ],
    Africa: [
      countryPricingData["South Africa"],
      countryPricingData["Nigeria"],
      countryPricingData["Egypt"],
      countryPricingData["Morocco"],
      countryPricingData["Kenya"],
      countryPricingData["Ghana"],
      countryPricingData["Ethiopia"],
      countryPricingData["Algeria"],
      countryPricingData["Tunisia"],
      countryPricingData["Uganda"],
      countryPricingData["Tanzania (TANU)"],
      countryPricingData["Zambia"],
      countryPricingData["Zimbabwe"],
      countryPricingData["Rwanda"],
      countryPricingData["Burundi"],
      countryPricingData["Mozambique"],
      countryPricingData["Angola"],
      countryPricingData["Madagascar"],
      countryPricingData["Namibia"],
      countryPricingData["Botswana"],
      countryPricingData["Libya"],
      countryPricingData["Sudan"],
      countryPricingData["Mauritania"],
      countryPricingData["Gambia"],
      countryPricingData["Seychelles"],
      countryPricingData["Djibouti"],
      countryPricingData["DR Congo"],
      countryPricingData["OAPI"],
      countryPricingData["ARIPO"],
      countryPricingData["Tanzania (ZAN)"],
    ],
    "Asia and Middle East": [
      countryPricingData["China"],
      countryPricingData["Japan"],
      countryPricingData["India"],
      countryPricingData["United Arab Emirates"],
      countryPricingData["Saudi Arabia"],
      countryPricingData["South Korea"],
      countryPricingData["Singapore"],
      countryPricingData["Thailand"],
      countryPricingData["Malaysia"],
      countryPricingData["Indonesia"],
      countryPricingData["Hong Kong"],
      countryPricingData["Taiwan"],
      countryPricingData["Vietnam"],
      countryPricingData["Philippines"],
      countryPricingData["Turkey"],
      countryPricingData["Israel"],
      countryPricingData["Qatar"],
      countryPricingData["Kuwait"],
      countryPricingData["Bahrain"],
      countryPricingData["Oman"],
      countryPricingData["Jordan"],
      countryPricingData["Lebanon"],
      countryPricingData["Iran"],
      countryPricingData["Iraq (Baghdad)"],
      countryPricingData["Iraq (Kurdistan)"],
      countryPricingData["Syria"],
      countryPricingData["Yemen"],
      countryPricingData["Pakistan"],
      countryPricingData["Bangladesh"],
      countryPricingData["Sri Lanka"],
      countryPricingData["Myanmar"],
      countryPricingData["Cambodia"],
      countryPricingData["Laos"],
      countryPricingData["Mongolia"],
      countryPricingData["Kazakhstan"],
      countryPricingData["Uzbekistan"],
      countryPricingData["Kyrgyzstan"],
      countryPricingData["Tajikistan"],
      countryPricingData["Turkmenistan"],
      countryPricingData["Armenia"],
      countryPricingData["Azerbaijan"],
      countryPricingData["Afghanistan"],
      countryPricingData["Nepal"],
      countryPricingData["Bhutan"],
      countryPricingData["Maldives"],
      countryPricingData["Brunei"],
      countryPricingData["Macao"],
      countryPricingData["North Korea"],
      countryPricingData["Palestine (Gaza)"],
      countryPricingData["Palestine (West Bank)"],
    ],
    Oceania: [countryPricingData["Papua New Guinea"], countryPricingData["Fiji"], countryPricingData["Tonga"]],
  }
}

export const countryPricing = countryPricingData
