export interface CountryPricing {
  name: string
  flag: string
  price: number
  additionalClassPrice: number
}

// Pricing data based on WIPO NICE Classification
export const countryPricingData: Record<string, CountryPricing> = {
  // Europe
  "European Union": { name: "European Union", flag: "eu", price: 1551, additionalClassPrice: 425 },
  Germany: { name: "Germany", flag: "de", price: 863, additionalClassPrice: 500 },
  Spain: { name: "Spain", flag: "es", price: 564, additionalClassPrice: 385 },
  "United Kingdom": { name: "United Kingdom", flag: "gb", price: 909, additionalClassPrice: 300 },
  France: { name: "France", flag: "fr", price: 667, additionalClassPrice: 190 },
  Italy: { name: "Italy", flag: "it", price: 920, additionalClassPrice: 180 },
  Benelux: { name: "Benelux", flag: "be", price: 794, additionalClassPrice: 190 },
  Portugal: { name: "Portugal", flag: "pt", price: 909, additionalClassPrice: 265 },
  Greece: { name: "Greece", flag: "gr", price: 736, additionalClassPrice: 570 },
  "Bosnia and Herzegovina": { name: "Bosnia and Herzegovina", flag: "ba", price: 656, additionalClassPrice: 170 },

  // North America
  "United States": { name: "United States", flag: "us", price: 1012, additionalClassPrice: 499 },
  Canada: { name: "Canada", flag: "ca", price: 1369, additionalClassPrice: 150 },
  Mexico: { name: "Mexico", flag: "mx", price: 685, additionalClassPrice: 540 },

  // South America
  Argentina: { name: "Argentina", flag: "ar", price: 460, additionalClassPrice: 350 },
  Bolivia: { name: "Bolivia", flag: "bo", price: 777, additionalClassPrice: 585 },
  Brazil: { name: "Brazil", flag: "br", price: 644, additionalClassPrice: 418 },
  Chile: { name: "Chile", flag: "cl", price: 689, additionalClassPrice: 499 },
  Colombia: { name: "Colombia", flag: "co", price: 794, additionalClassPrice: 490 },
  Ecuador: { name: "Ecuador", flag: "ec", price: 632, additionalClassPrice: 549 },
  Paraguay: { name: "Paraguay", flag: "py", price: 564, additionalClassPrice: 399 },
  Peru: { name: "Peru", flag: "pe", price: 667, additionalClassPrice: 570 },
  Uruguay: { name: "Uruguay", flag: "uy", price: 604, additionalClassPrice: 299 },
  Venezuela: { name: "Venezuela", flag: "ve", price: 604, additionalClassPrice: 510 },

  // Central America
  Belize: { name: "Belize", flag: "bz", price: 915, additionalClassPrice: 980 },
  "Costa Rica": { name: "Costa Rica", flag: "cr", price: 529, additionalClassPrice: 299 },
  "El Salvador": { name: "El Salvador", flag: "sv", price: 570, additionalClassPrice: 650 },
  Guatemala: { name: "Guatemala", flag: "gt", price: 599, additionalClassPrice: 520 },
  Honduras: { name: "Honduras", flag: "hn", price: 685, additionalClassPrice: 750 },
  Nicaragua: { name: "Nicaragua", flag: "ni", price: 621, additionalClassPrice: 700 },
  Panama: { name: "Panama", flag: "pa", price: 621, additionalClassPrice: 440 },

  // Caribbean
  Anguilla: { name: "Anguilla", flag: "ai", price: 1012, additionalClassPrice: 430 },
  "Antigua and Barbuda": { name: "Antigua and Barbuda", flag: "ag", price: 759, additionalClassPrice: 330 },
  Aruba: { name: "Aruba", flag: "aw", price: 943, additionalClassPrice: 170 },
  Bahamas: { name: "Bahamas", flag: "bs", price: 1076, additionalClassPrice: 935 },
  Barbados: { name: "Barbados", flag: "bb", price: 1400, additionalClassPrice: 1150 },
  Bermuda: { name: "Bermuda", flag: "bm", price: 1770, additionalClassPrice: 1539 },
  "BES Islands": { name: "BES Islands", flag: "bq", price: 874, additionalClassPrice: 199 },
  "British Virgin Islands": { name: "British Virgin Islands", flag: "vg", price: 1001, additionalClassPrice: 480 },
  "Cayman Islands": { name: "Cayman Islands", flag: "ky", price: 1242, additionalClassPrice: 350 },
  Cuba: { name: "Cuba", flag: "cu", price: 1375, additionalClassPrice: 730 },
  Curacao: { name: "Curacao", flag: "cw", price: 1208, additionalClassPrice: 200 },
  Dominica: { name: "Dominica", flag: "dm", price: 1024, additionalClassPrice: 530 },
  "Dominican Republic": { name: "Dominican Republic", flag: "do", price: 621, additionalClassPrice: 420 },
  Grenada: { name: "Grenada", flag: "gd", price: 1145, additionalClassPrice: 280 },
  Guyana: { name: "Guyana", flag: "gy", price: 564, additionalClassPrice: 210 },
  Haiti: { name: "Haiti", flag: "ht", price: 736, additionalClassPrice: 430 },
  Jamaica: { name: "Jamaica", flag: "jm", price: 1231, additionalClassPrice: 355 },
  Montserrat: { name: "Montserrat", flag: "ms", price: 742, additionalClassPrice: 315 },
  "Puerto Rico": { name: "Puerto Rico", flag: "pr", price: 817, additionalClassPrice: 680 },
  "Saint Kitts and Nevis": { name: "Saint Kitts and Nevis", flag: "kn", price: 1070, additionalClassPrice: 390 },
  "Saint Lucia": { name: "Saint Lucia", flag: "lc", price: 1024, additionalClassPrice: 390 },
  "Saint Vincent and the Grenadines": {
    name: "Saint Vincent and the Grenadines",
    flag: "vc",
    price: 656,
    additionalClassPrice: 570,
  },
  "Sint Maarten": { name: "Sint Maarten", flag: "sx", price: 1254, additionalClassPrice: 200 },
  Suriname: { name: "Suriname", flag: "sr", price: 874, additionalClassPrice: 160 },
  "Trinidad and Tobago": { name: "Trinidad and Tobago", flag: "tt", price: 828, additionalClassPrice: 250 },
  "Turks and Caicos Islands": { name: "Turks and Caicos Islands", flag: "tc", price: 2128, additionalClassPrice: 1850 },

  // Africa
  Algeria: { name: "Algeria", flag: "dz", price: 990, additionalClassPrice: 990 },
  Angola: { name: "Angola", flag: "ao", price: 1050, additionalClassPrice: 1050 },
  ARIPO: { name: "ARIPO", flag: "zw", price: 3150, additionalClassPrice: 3150 },
  Botswana: { name: "Botswana", flag: "bw", price: 1090, additionalClassPrice: 1090 },
  Burundi: { name: "Burundi", flag: "bi", price: 1550, additionalClassPrice: 1550 },
  Djibouti: { name: "Djibouti", flag: "dj", price: 2050, additionalClassPrice: 2050 },
  Egypt: { name: "Egypt", flag: "eg", price: 765, additionalClassPrice: 765 },
  Ethiopia: { name: "Ethiopia", flag: "et", price: 1290, additionalClassPrice: 1290 },
  Gambia: { name: "Gambia", flag: "gm", price: 1350, additionalClassPrice: 1350 },
  Ghana: { name: "Ghana", flag: "gh", price: 1499, additionalClassPrice: 1499 },
  Kenya: { name: "Kenya", flag: "ke", price: 1600, additionalClassPrice: 1600 },
  Libya: { name: "Libya", flag: "ly", price: 1100, additionalClassPrice: 1100 },
  Madagascar: { name: "Madagascar", flag: "mg", price: 1050, additionalClassPrice: 1050 },
  Morocco: { name: "Morocco", flag: "ma", price: 1050, additionalClassPrice: 1050 },
  Mauritania: { name: "Mauritania", flag: "mr", price: 1190, additionalClassPrice: 1190 },
  Mozambique: { name: "Mozambique", flag: "mz", price: 1050, additionalClassPrice: 1050 },
  Namibia: { name: "Namibia", flag: "na", price: 1100, additionalClassPrice: 1100 },
  Nigeria: { name: "Nigeria", flag: "ng", price: 1150, additionalClassPrice: 1150 },
  OAPI: { name: "OAPI", flag: "sn", price: 1690, additionalClassPrice: 1690 },
  "DR Congo": { name: "DR Congo", flag: "cd", price: 1199, additionalClassPrice: 1199 },
  Rwanda: { name: "Rwanda", flag: "rw", price: 1350, additionalClassPrice: 1350 },
  Seychelles: { name: "Seychelles", flag: "sc", price: 1150, additionalClassPrice: 1150 },
  "South Africa": { name: "South Africa", flag: "za", price: 1110, additionalClassPrice: 1110 },
  Sudan: { name: "Sudan", flag: "sd", price: 1050, additionalClassPrice: 1050 },
  "Tanzania (TANU)": { name: "Tanzania (TANU)", flag: "tz", price: 1000, additionalClassPrice: 1000 },
  "Tanzania (ZAN)": { name: "Tanzania (ZAN)", flag: "tz", price: 1050, additionalClassPrice: 1050 },
  Tunisia: { name: "Tunisia", flag: "tn", price: 990, additionalClassPrice: 990 },
  Uganda: { name: "Uganda", flag: "ug", price: 1850, additionalClassPrice: 1850 },
  Zambia: { name: "Zambia", flag: "zm", price: 1299, additionalClassPrice: 1299 },
  Zimbabwe: { name: "Zimbabwe", flag: "zw", price: 1350, additionalClassPrice: 1350 },

  // Asia and Middle East
  Afghanistan: { name: "Afghanistan", flag: "af", price: 863, additionalClassPrice: 1090 },
  "Saudi Arabia": { name: "Saudi Arabia", flag: "sa", price: 2818, additionalClassPrice: 2450 },
  Armenia: { name: "Armenia", flag: "am", price: 1495, additionalClassPrice: 1300 },
  Azerbaijan: { name: "Azerbaijan", flag: "az", price: 1001, additionalClassPrice: 470 },
  Bahrain: { name: "Bahrain", flag: "bh", price: 3013, additionalClassPrice: 2620 },
  Bangladesh: { name: "Bangladesh", flag: "bd", price: 892, additionalClassPrice: 775 },
  Bhutan: { name: "Bhutan", flag: "bt", price: 690, additionalClassPrice: 380 },
  Brunei: { name: "Brunei", flag: "bn", price: 863, additionalClassPrice: 750 },
  Cambodia: { name: "Cambodia", flag: "kh", price: 724, additionalClassPrice: 629 },
  "Hong Kong": { name: "Hong Kong", flag: "hk", price: 978, additionalClassPrice: 490 },
  India: { name: "India", flag: "in", price: 662, additionalClassPrice: 450 },
  Indonesia: { name: "Indonesia", flag: "id", price: 1139, additionalClassPrice: 950 },
  Iran: { name: "Iran", flag: "ir", price: 1725, additionalClassPrice: 490 },
  "Iraq (Baghdad)": { name: "Iraq (Baghdad)", flag: "iq", price: 1737, additionalClassPrice: 300 },
  "Iraq (Kurdistan)": { name: "Iraq (Kurdistan)", flag: "iq", price: 2012, additionalClassPrice: 1749 },
  Japan: { name: "Japan", flag: "jp", price: 777, additionalClassPrice: 500 },
  Jordan: { name: "Jordan", flag: "jo", price: 1495, additionalClassPrice: 1300 },
  Kazakhstan: { name: "Kazakhstan", flag: "kz", price: 920, additionalClassPrice: 430 },
  Kyrgyzstan: { name: "Kyrgyzstan", flag: "kg", price: 851, additionalClassPrice: 520 },
  "South Korea": { name: "South Korea", flag: "kr", price: 804, additionalClassPrice: 600 },
  Kuwait: { name: "Kuwait", flag: "kw", price: 2093, additionalClassPrice: 1820 },
  Laos: { name: "Laos", flag: "la", price: 736, additionalClassPrice: 640 },
  Lebanon: { name: "Lebanon", flag: "lb", price: 1012, additionalClassPrice: 470 },
  Macao: { name: "Macao", flag: "mo", price: 886, additionalClassPrice: 770 },
  Malaysia: { name: "Malaysia", flag: "my", price: 1323, additionalClassPrice: 970 },
  Maldives: { name: "Maldives", flag: "mv", price: 1024, additionalClassPrice: 490 },
  Mongolia: { name: "Mongolia", flag: "mn", price: 782, additionalClassPrice: 480 },
  Myanmar: { name: "Myanmar", flag: "mm", price: 725, additionalClassPrice: 520 },
  Nepal: { name: "Nepal", flag: "np", price: 725, additionalClassPrice: 630 },
  "North Korea": { name: "North Korea", flag: "kp", price: 1553, additionalClassPrice: 570 },
  Oman: { name: "Oman", flag: "om", price: 1645, additionalClassPrice: 1430 },
  Pakistan: { name: "Pakistan", flag: "pk", price: 863, additionalClassPrice: 690 },
  "Palestine (Gaza)": { name: "Palestine (Gaza)", flag: "ps", price: 1012, additionalClassPrice: 880 },
  "Palestine (West Bank)": { name: "Palestine (West Bank)", flag: "ps", price: 966, additionalClassPrice: 840 },
  Philippines: { name: "Philippines", flag: "ph", price: 748, additionalClassPrice: 530 },
  Qatar: { name: "Qatar", flag: "qa", price: 2507, additionalClassPrice: 2180 },
  Singapore: { name: "Singapore", flag: "sg", price: 1024, additionalClassPrice: 750 },
  Syria: { name: "Syria", flag: "sy", price: 2013, additionalClassPrice: 1750 },
  "Sri Lanka": { name: "Sri Lanka", flag: "lk", price: 685, additionalClassPrice: 595 },
  Taiwan: { name: "Taiwan", flag: "tw", price: 817, additionalClassPrice: 710 },
  Tajikistan: { name: "Tajikistan", flag: "tj", price: 2012, additionalClassPrice: 1749 },
  Thailand: { name: "Thailand", flag: "th", price: 1380, additionalClassPrice: 1000 },
  Turkey: { name: "Turkey", flag: "tr", price: 644, additionalClassPrice: 265 },
  Turkmenistan: { name: "Turkmenistan", flag: "tm", price: 1145, additionalClassPrice: 545 },
  "United Arab Emirates": { name: "United Arab Emirates", flag: "ae", price: 2990, additionalClassPrice: 2475 },
  Uzbekistan: { name: "Uzbekistan", flag: "uz", price: 1541, additionalClassPrice: 590 },
  Vietnam: { name: "Vietnam", flag: "vn", price: 575, additionalClassPrice: 500 },
  Yemen: { name: "Yemen", flag: "ye", price: 1840, additionalClassPrice: 1600 },
  China: { name: "China", flag: "cn", price: 518, additionalClassPrice: 450 },
  Israel: { name: "Israel", flag: "il", price: 1495, additionalClassPrice: 1300 },

  // Oceania
  "Papua New Guinea": { name: "Papua New Guinea", flag: "pg", price: 1350, additionalClassPrice: 1200 },
  Fiji: { name: "Fiji", flag: "fj", price: 1150, additionalClassPrice: 1000 },
  Tonga: { name: "Tonga", flag: "to", price: 1250, additionalClassPrice: 1100 },
}

// Helper function to get top requested countries
export const getTopCountries = (): CountryPricing[] => {
  return [
    countryPricingData["European Union"],
    countryPricingData["United States"],
    countryPricingData["Germany"],
    countryPricingData["Spain"],
    countryPricingData["United Kingdom"],
    countryPricingData["China"],
  ]
}

// Helper function to get countries by region
export const getCountriesByRegion = () => {
  return {
    "North America": [countryPricingData["United States"], countryPricingData["Canada"], countryPricingData["Mexico"]],
    Europe: [
      countryPricingData["European Union"],
      countryPricingData["Spain"],
      countryPricingData["France"],
      countryPricingData["United Kingdom"],
      countryPricingData["Italy"],
      countryPricingData["Germany"],
      countryPricingData["Portugal"],
      countryPricingData["Greece"],
      countryPricingData["Benelux"],
      countryPricingData["Bosnia and Herzegovina"],
    ],
    "South America": [
      countryPricingData["Argentina"],
      countryPricingData["Brazil"],
      countryPricingData["Chile"],
      countryPricingData["Colombia"],
      countryPricingData["Ecuador"],
      countryPricingData["Paraguay"],
      countryPricingData["Peru"],
      countryPricingData["Uruguay"],
      countryPricingData["Venezuela"],
      countryPricingData["Bolivia"],
    ],
    "Central America": [
      countryPricingData["Costa Rica"],
      countryPricingData["Panama"],
      countryPricingData["Guatemala"],
      countryPricingData["El Salvador"],
      countryPricingData["Honduras"],
      countryPricingData["Nicaragua"],
      countryPricingData["Belize"],
    ],
    Caribbean: [
      countryPricingData["Jamaica"],
      countryPricingData["Dominican Republic"],
      countryPricingData["Cuba"],
      countryPricingData["Bahamas"],
      countryPricingData["Barbados"],
      countryPricingData["Trinidad and Tobago"],
      countryPricingData["Aruba"],
      countryPricingData["Curacao"],
      countryPricingData["Antigua and Barbuda"],
      countryPricingData["Saint Lucia"],
      countryPricingData["Grenada"],
      countryPricingData["Saint Kitts and Nevis"],
      countryPricingData["Dominica"],
      countryPricingData["Saint Vincent and the Grenadines"],
      countryPricingData["Bermuda"],
      countryPricingData["Cayman Islands"],
      countryPricingData["British Virgin Islands"],
      countryPricingData["Turks and Caicos Islands"],
      countryPricingData["Anguilla"],
      countryPricingData["Montserrat"],
      countryPricingData["Sint Maarten"],
      countryPricingData["BES Islands"],
      countryPricingData["Guyana"],
      countryPricingData["Suriname"],
      countryPricingData["Haiti"],
      countryPricingData["Puerto Rico"],
    ],
    Africa: [
      countryPricingData["South Africa"],
      countryPricingData["Nigeria"],
      countryPricingData["Egypt"],
      countryPricingData["Morocco"],
      countryPricingData["Kenya"],
      countryPricingData["Ghana"],
      countryPricingData["Ethiopia"],
      countryPricingData["Algeria"],
      countryPricingData["Tunisia"],
      countryPricingData["Uganda"],
      countryPricingData["Tanzania (TANU)"],
      countryPricingData["Zambia"],
      countryPricingData["Zimbabwe"],
      countryPricingData["Rwanda"],
      countryPricingData["Burundi"],
      countryPricingData["Mozambique"],
      countryPricingData["Angola"],
      countryPricingData["Madagascar"],
      countryPricingData["Namibia"],
      countryPricingData["Botswana"],
      countryPricingData["Libya"],
      countryPricingData["Sudan"],
      countryPricingData["Mauritania"],
      countryPricingData["Gambia"],
      countryPricingData["Seychelles"],
      countryPricingData["Djibouti"],
      countryPricingData["DR Congo"],
      countryPricingData["OAPI"],
      countryPricingData["ARIPO"],
      countryPricingData["Tanzania (ZAN)"],
    ],
    "Asia and Middle East": [
      countryPricingData["China"],
      countryPricingData["Japan"],
      countryPricingData["India"],
      countryPricingData["United Arab Emirates"],
      countryPricingData["Saudi Arabia"],
      countryPricingData["South Korea"],
      countryPricingData["Singapore"],
      countryPricingData["Thailand"],
      countryPricingData["Malaysia"],
      countryPricingData["Indonesia"],
      countryPricingData["Hong Kong"],
      countryPricingData["Taiwan"],
      countryPricingData["Vietnam"],
      countryPricingData["Philippines"],
      countryPricingData["Turkey"],
      countryPricingData["Israel"],
      countryPricingData["Qatar"],
      countryPricingData["Kuwait"],
      countryPricingData["Bahrain"],
      countryPricingData["Oman"],
      countryPricingData["Jordan"],
      countryPricingData["Lebanon"],
      countryPricingData["Iran"],
      countryPricingData["Iraq (Baghdad)"],
      countryPricingData["Iraq (Kurdistan)"],
      countryPricingData["Syria"],
      countryPricingData["Yemen"],
      countryPricingData["Pakistan"],
      countryPricingData["Bangladesh"],
      countryPricingData["Sri Lanka"],
      countryPricingData["Myanmar"],
      countryPricingData["Cambodia"],
      countryPricingData["Laos"],
      countryPricingData["Mongolia"],
      countryPricingData["Kazakhstan"],
      countryPricingData["Uzbekistan"],
      countryPricingData["Kyrgyzstan"],
      countryPricingData["Tajikistan"],
      countryPricingData["Turkmenistan"],
      countryPricingData["Armenia"],
      countryPricingData["Azerbaijan"],
      countryPricingData["Afghanistan"],
      countryPricingData["Nepal"],
      countryPricingData["Bhutan"],
      countryPricingData["Maldives"],
      countryPricingData["Brunei"],
      countryPricingData["Macao"],
      countryPricingData["North Korea"],
      countryPricingData["Palestine (Gaza)"],
      countryPricingData["Palestine (West Bank)"],
    ],
    Oceania: [countryPricingData["Papua New Guinea"], countryPricingData["Fiji"], countryPricingData["Tonga"]],
  }
}

export const countryPricing = countryPricingData
