// Sample data for trademark searches
export const sampleSearches = [
  {
    id: "sample-1",
    form_type: "Free Search",
    search_data: {
      trademarkName: "InnovateTech",
      firstName: "Juan",
      lastName: "Pérez",
      email: "juan.perez@example.com",
      goodsAndServices: "Software development and consulting services",
    },
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    status: "pending",
    results: undefined,
  },
  {
    id: "sample-2",
    form_type: "Registration",
    search_data: {
      trademarkName: "EcoSolutions",
      firstName: "María",
      lastName: "García",
      email: "maria.garcia@example.com",
      goodsAndServices: "Environmental consulting and sustainable product development",
    },
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: "processing",
    results: {
      similarTrademarks: ["EcoSolve", "EcoSolution Pro"],
      comments: "There are some similar trademarks in the database, but they are in different classes.",
      recommendation: "We recommend registering this trademark in classes 35, 42.",
      verificationToken: "token123456789",
    },
  },
  {
    id: "sample-3",
    form_type: "Free Search",
    search_data: {
      trademarkName: "GourmetDelight",
      firstName: "Carlos",
      lastName: "Rodríguez",
      email: "carlos.rodriguez@example.com",
      goodsAndServices: "Gourmet food products and catering services",
    },
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: "completed",
    results: {
      similarTrademarks: ["DelightGourmet", "Gourmet Delights Inc."],
      comments: "There are similar trademarks in the food industry, but your specific combination is unique.",
      recommendation: "We recommend registering this trademark in classes 29, 30, 43.",
      verificationToken: "token987654321",
    },
  },
  {
    id: "sample-4",
    form_type: "Registration",
    search_data: {
      trademarkName: "FitLife",
      firstName: "Ana",
      lastName: "Martínez",
      email: "ana.martinez@example.com",
      goodsAndServices: "Fitness equipment, apparel, and personal training services",
    },
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    status: "rejected",
    results: {
      similarTrademarks: ["FitLife Pro", "FitLife International", "FitLifeStyle"],
      comments: "There are multiple existing trademarks that are very similar to your proposed trademark.",
      recommendation: "",
      verificationToken: "token456789123",
    },
  },
  {
    id: "sample-5",
    form_type: "Free Search",
    search_data: {
      trademarkName: "ArtisanCraft",
      firstName: "Pedro",
      lastName: "Sánchez",
      email: "pedro.sanchez@example.com",
      goodsAndServices: "Handcrafted furniture and home decor items",
    },
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    status: "pending",
    results: undefined,
  },
]
